#!/usr/bin/env bash
# ==============================================================================
# Script de Pós-Instalação e Restauração de Sistema - Kubuntu
# ==============================================================================

set -e

echo "=== 1. Atualizando listas de repositórios e sistema ==="
sudo apt update && sudo apt upgrade -y

echo "=== 2. Habilitando repositórios oficiais adicionais ==="
sudo add-apt-repository multiverse -y
sudo add-apt-repository restricted -y
sudo apt update

echo "=== 3. Instalando suporte básico, chaves GPG e suporte a Flatpak ==="
sudo mkdir -p /etc/apt/keyrings
sudo apt install -y curl ca-certificates gnupg flatpak snapd

# Habilita e inicia o serviço do Snapd
sudo systemctl enable --now snapd.socket

# Adiciona o repositório Flathub para o Flatpak
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "=== 4. Adicionando Repositórios de Terceiros ==="

# 4.1. Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc --yes
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# 4.2. Sublime Text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/sublime.gpg --yes
echo "deb [signed-by=/etc/apt/keyrings/sublime.gpg] https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list > /dev/null

# 4.3. VS Code (Microsoft)
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg --yes
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null

# 4.4. PPA Conky Manager 2
sudo add-apt-repository ppa:ubuntuhandbook1/conkymanager2 -y

# Atualiza listas após adição de PPAs
sudo apt update

echo "=== 5. Aceitando termos de licença automáticos ==="
echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections

# ==============================================================================
# SEÇÃO JAVA (JRE, JDK, FERRAMENTAS E UTILITÁRIOS)
# ==============================================================================

# ------------------------------------------------------------------------------
# OPCÃO A: INSTALAÇÃO PADRÃO DA DISTRIBUIÇÃO (Metapacote)
# ------------------------------------------------------------------------------
# Instala a versão padrão recomendada pelo repositório do sistema.
# sudo apt update && sudo apt install -y default-jre default-jdk default-jdk-doc

# ------------------------------------------------------------------------------
# OPÇÃO B: JRE - RUNTIME ENVIRONMENT (Escolha e descomente o desejado)
# ------------------------------------------------------------------------------
# sudo apt install -y openjdk-8-jre-headless
# sudo apt install -y openjdk-11-jre-headless
# sudo apt install -y openjdk-17-jre-headless
# sudo apt install -y openjdk-17-crac-jre-headless
# sudo apt install -y openjdk-21-jre-headless
# sudo apt install -y openjdk-21-crac-jre-headless
# sudo apt install -y openjdk-22-jre-headless
# sudo apt install -y openjdk-23-jre-headless
# sudo apt install -y openjdk-24-jre-headless

# ------------------------------------------------------------------------------
# OPÇÃO C: JDK - DEVELOPMENT KIT (Escolha e descomente o desejado)
# ------------------------------------------------------------------------------
# OpenJDK 11 (LTS)
# sudo apt install -y openjdk-11-jdk openjdk-11-doc

# OpenJDK 17 (LTS - Amplamente utilizado em ambiente corporativo/legado)
# sudo apt install -y openjdk-17-jdk openjdk-17-doc openjdk-17-demo openjdk-17-source

# OpenJDK 21 (LTS - Versão atual recomendada para desenvolvimento moderno)
sudo apt install -y openjdk-21-jdk openjdk-21-doc

# ------------------------------------------------------------------------------
# FERRAMENTAS ADICIONAIS DE DESENVOLVIMENTO E PROFILING
# ------------------------------------------------------------------------------
# jtreg: Suíte de testes do OpenJDK
# libasmtools-java: Utilitário para manipulação e análise de bytecode
# visualvm: Ferramenta visual para monitoramento, análise de desempenho e profilagem
sudo apt install -y jtreg libasmtools-java visualvm

# ------------------------------------------------------------------------------
# GERENCIAMENTO DE VERSÕES E VARIÁVEIS DE AMBIENTE (Pós-instalação)
# ------------------------------------------------------------------------------
# Caso tenha mais de uma versão do Java instalada no sistema, 
# use os comandos abaixo para alternar entre elas interativamente:
#
# sudo update-alternatives --config java
# sudo update-alternatives --config javac
#
# Para conferir a versão ativa no terminal:
# java -version

echo "=== 6. Instalando pacotes e bibliotecas via APT ==="

PACOTES_APT=(
  3cpio
  7zip
  aapt
  abootimg
  accountsservice
  accountwizard
  acct
  acl
  adduser
  advancecomp
  adwaita-icon-theme
  aesfix
  aeskeyfind
  afflib-tools
  aha
  aircrack-ng
  airgraph-ng
  akonadi-backend-sqlite
  akonadi-contacts-data
  akonadi-mime-data
  akonadi-server
  akonadiconsole
  akregator
  alligator
  alsa-base
  alsa-topology-conf
  alsa-ucm-conf
  alsa-utils
  altdns
  amd64-microcode
  anacron
  analitza-common
  ancient
  androguard
  android-framework-res
  android-libaapt
  android-libandroidfw
  android-libart
  android-libbacktrace
  android-libbase
  android-libcutils
  android-liblog
  android-libnativebridge
  android-libnativeloader
  android-libutils
  android-libziparchive
  ansifilter
  ansifilter-gui
  ant
  ant-optional
  antlr3
  apksigcopier
  apksigner
  apktool
  apparmor
  appmenu-gtk-module-common
  appmenu-gtk3-module
  apport
  apport-kde
  apport-symptoms
  appstream
  apt
  apt-config-icons
  apt-config-icons-hidpi
  apt-config-icons-large
  apt-config-icons-large-hidpi
  apt-transport-https
  aptitude
  aptitude-common
  arc
  ardour
  ardour-data
  ardour-lv2-plugins
  ardour-video-timeline
  argon2
  arj
  ark
  arqiver
  artikulate
  aspell
  aspell-en
  aspell-pt-br
  assetfinder
  assistant-qt6
  at-spi2-common
  at-spi2-core
  attr
  audacity
  audacity-data
  augeas-lenses
  avahi-daemon
  baloo6
  base-files
  base-passwd
  bash
  bash-completion
  bc
  bfbtester
  bind9-dnsutils
  bind9-host
  bind9-libs
  binutils
  binutils-common
  binutils-multiarch
  binutils-x86-64-linux-gnu
  binwalk
  bleachbit
  blinken
  bluedevil
  bluefish
  bluefish-data
  bluefish-plugins
  bluez
  bluez-cups
  bluez-obexd
  bolt
  bomber
  bovo
  bpfcc-tools
  bpftool
  bpftrace
  braa
  breeze
  breeze-cursor-theme
  breeze-gtk-theme
  breeze-wallpaper
  brotli
  bruteforce-luks
  bruteforce-salted-openssl
  bruteforce-wallet
  brutespray
  bsd-mailx
  bsdextrautils
  bsdutils
  btrfs-progs
  btscanner
  bubblewrap
  build-essential
  bully
  bup
  bup-doc
  busybox-initramfs
  busybox-static
  bzip2
  bzip2-doc
  bzip3
  c-icap
  ca-certificates
  ca-certificates-java
  cabextract
  caca-utils
  calibre
  calibre-bin
  cantor
  cantor-backend-qalculate
  capstone-tool
  catdoc
  ccrypt
  certisign-websigner
  cewl
  chafa
  chaosreader
  chkrootkit
  chntpw
  chrony
  cisco7crack
  clamav
  clamav-base
  clamav-cvdupdate
  clamav-daemon
  clamav-doc
  clamav-docs
  clamav-freshclam
  clamav-testfiles
  clamav-testfiles-rar
  clamdscan
  clamtk
  clang-18
  clang-21
  clang-tools-21
  clevis
  clevis-luks
  clinfo
  clzip
  cmake
  cmake-data
  cmake-qt-gui
  cmospwd
  colord
  colord-data
  command-not-found
  comprez
  conky-all
  conky-manager2
  console-setup
  console-setup-linux
  containerd.io
  coreboot-utils
  coreutils
  coreutils-from-uutils
  cowpatty
  cpio
  cpp
  cpp-15
  cpp-15-x86-64-linux-gnu
  cpp-x86-64-linux-gnu
  cpu-checker
  crac-criu
  cracklib-runtime
  cramfsswap
  creddump7
  cron
  cron-daemon-common
  crunch
  cryfs
  cryptmount
  cryptsetup
  cryptsetup-bin
  cryptsetup-initramfs
  cupp
  cups
  cups-browsed
  cups-bsd
  cups-client
  cups-common
  cups-core-drivers
  cups-daemon
  cups-filters
  cups-filters-core-drivers
  cups-ipp-utils
  cups-pk-helper
  cups-ppdc
  cups-server-common
  curl
  dact
  dares
  darktable
  dash
  db-util
  db5.3-util
  dbus
  dbus-bin
  dbus-daemon
  dbus-session-bus-common
  dbus-system-bus-common
  dbus-user-session
  dbus-x11
  dc
  dc3dd
  dcfldd
  dconf-cli
  dconf-gsettings-backend
  dconf-service
  dcraw
  ddrescueview
  ddrutility
  debconf
  debconf-i18n
  debconf-kde-data
  debconf-kde-helper
  debianutils
  default-jdk
  default-jdk-doc
  default-jdk-headless
  default-jre
  default-jre-headless
  designer-qt6
  desktop-file-utils
  device-tree-compiler
  dexdump
  dhcpcd-base
  dhcpdump
  dictconv
  dictionaries-common
  dictzip
  diffoscope
  diffoscope-minimal
  diffstat
  diffutils
  dirb
  dirmngr
  disktype
  dislocker
  distro-info
  distro-info-data
  dmeventd
  dmidecode
  dmitry
  dmsetup
  dns-root-data
  dnsmasq-base
  dnsrecon
  docbook-xml
  docbook-xsl
  docker-buildx-plugin
  docker-ce
  docker-ce-cli
  docker-ce-rootless-extras
  docker-compose-plugin
  docx2txt
  dolphin
  dolphin-data
  dolphin-doc
  dolphin-plugins
  doona
  dosfstools
  dpkg
  dpkg-dev
  dracut-install
  dragonplayer
  drkonqi
  dsniff
  dtach
  dupeguru
  dvisvgm
  e2fsprogs
  easyssh
  ed
  ed2k-hash
  edict
  edid-decode
  efibootmgr
  eject
  elfutils
  elisa
  emacsen-common
  enchant-2
  enjarify
  erofs-utils
  espeak-ng-data
  ethstatus
  ethtool
  evemu-tools
  evince
  evince-common
  evolution-data-server-common
  evtest
  ewf-tools
  exfatprogs
  exif
  exiflooter
  exifprobe
  exiftags
  exiv2
  ext3grep
  ext4magic
  extlinux
  extundelete
  f2fs-tools
  fakeroot
  fastfetch
  fatcat
  fcrackzip
  fdisk
  fdupes
  ffmpeg
  ffmpegthumbs
  fig2dev
  file
  filelight
  finalrd
  findutils
  firebird-utils
  firebird4.0-common
  firebird4.0-common-doc
  firebird4.0-server-core
  firebird4.0-utils
  firmware-sof-signed
  flac
  fluid-soundfont-gm
  fontconfig
  fontconfig-config
  fontforge-common
  fontforge-extras
  fonts-cantarell
  fonts-crosextra-caladea
  fonts-crosextra-carlito
  fonts-dejavu
  fonts-dejavu-core
  fonts-dejavu-extra
  fonts-dejavu-mono
  fonts-droid-fallback
  fonts-dustin
  fonts-font-awesome
  fonts-freefont-ttf
  fonts-hack
  fonts-ibm-plex
  fonts-inconsolata
  fonts-kanjistrokeorders
  fonts-lato
  fonts-liberation
  fonts-liberation-sans-narrow
  fonts-linuxlibertine
  fonts-lmodern
  fonts-lyx
  fonts-noto-cjk
  fonts-noto-color-emoji
  fonts-noto-core
  fonts-noto-extra
  fonts-noto-hinted
  fonts-noto-mono
  fonts-noto-ui-core
  fonts-noto-unhinted
  fonts-opensymbol
  fonts-sil-gentium
  fonts-sil-gentium-basic
  fonts-sjfonts
  fonts-tuffy
  fonts-ubuntu
  fonts-urw-base35
  fonts-vlgothic
  fonttools
  foomatic-db-compressed-ppds
  foremost
  forensic-artifacts
  forensics-all
  forensics-all-gui
  forensics-colorize
  forensics-extra
  fortune-mod
  fortunes
  fortunes-br
  fortunes-min
  fp-compiler-3.2.2
  fp-units-rtl-3.2.2
  fp-utils
  fp-utils-3.2.2
  fprintd
  frameworkintegration6
  freepats
  freetds-common
  freetuxtv
  frei0r-plugins
  friendly-recovery
  ftp
  funcoeszz
  fuse3
  fwupd
  fwupd-signed
  g++
  g++-15
  g++-15-x86-64-linux-gnu
  g++-x86-64-linux-gnu
  galleta
  gawk
  gcc
  gcc-15
  gcc-15-base
  gcc-15-x86-64-linux-gnu
  gcc-16-base
  gcc-x86-64-linux-gnu
  gdal-data
  gdal-plugins
  gdb
  gddrescue
  gdebi
  gdebi-core
  gdisk
  gedit
  gedit-common
  genisoimage
  geoclue-2.0
  geocode-glib-common
  geoip-bin
  geoip-database
  gettext
  gettext-base
  gfortran
  gfortran-15
  gfortran-15-x86-64-linux-gnu
  gfortran-x86-64-linux-gnu
  ghc
  ghostscript
  giflib-tools
  gifshuffle
  gimp
  gimp-data
  gimp-data-extras
  gimp-help-common
  gimp-help-pt-br
  gir1.2-adw-1
  gir1.2-amtk-5
  gir1.2-atk-1.0
  gir1.2-atspi-2.0
  gir1.2-babl-0.1
  gir1.2-freedesktop
  gir1.2-gdkpixbuf-2.0
  gir1.2-gegl-0.4
  gir1.2-geoclue-2.0
  gir1.2-geocodeglib-2.0
  gir1.2-gexiv2-0.10
  gir1.2-gimp-3.0
  gir1.2-girepository-3.0
  gir1.2-glib-2.0
  gir1.2-glib-2.0-dev
  gir1.2-graphene-1.0
  gir1.2-gstreamer-1.0
  gir1.2-gtk-3.0
  gir1.2-gtk-4.0
  gir1.2-gtksource-300
  gir1.2-gtksource-4
  gir1.2-gudev-1.0
  gir1.2-gweather-4.0
  gir1.2-harfbuzz-0.0
  gir1.2-json-1.0
  gir1.2-notify-0.7
  gir1.2-packagekitglib-1.0
  gir1.2-pango-1.0
  gir1.2-poppler-0.18
  gir1.2-rest-1.0
  gir1.2-secret-1
  gir1.2-shumate-1.0
  gir1.2-soup-3.0
  gir1.2-tepl-6
  gir1.2-vte-2.91
  gir1.2-wnck-3.0
  gir1.2-xdp-1.0
  girepository-tools
  git
  git-man
  gjs
  glib-networking
  glib-networking-common
  glib-networking-services
  glycin-loaders
  glycin-thumbnailers
  gnome-accessibility-themes
  gnome-desktop3-data
  gnome-maps
  gnome-themes-extra
  gnome-themes-extra-data
  gnu-coreutils
  gnuchess
  gnuchess-book
  gnugo
  gnumeric
  gnumeric-common
  gnumeric-doc
  gnupg
  gnupg-agent
  gnupg-l10n
  gnupg-utils
  gnustep-base-common
  gnustep-base-runtime
  gnustep-common
  gnustep-multiarch
  gnutls-bin
  go-mtpfs
  gobuster
  gocryptfs
  google-chrome-stable
  gostsum
  gpart
  gpg
  gpg-agent
  gpg-wks-client
  gpgconf
  gpgsm
  gpgv
  gpshell
  granatier
  graphviz
  graudit
  grep
  groff-base
  grokevt
  grub-common
  grub-efi-amd64-bin
  grub-efi-amd64-signed
  grub-efi-amd64-unsigned
  grub-gfxpayload-lists
  grub-pc
  grub-pc-bin
  grub-theme-breeze
  grub2-common
  gsettings-desktop-schemas
  gstreamer1.0-gl
  gstreamer1.0-gtk3
  gstreamer1.0-libav
  gstreamer1.0-pipewire
  gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-base
  gstreamer1.0-plugins-extra
  gstreamer1.0-plugins-good
  gstreamer1.0-plugins-ugly
  gstreamer1.0-qt6
  gstreamer1.0-x
  gtk-update-icon-cache
  gtk2-engines-pixbuf
  guestfish
  guestfs-tools
  guestmount
  gufw
  guymager
  gvfs
  gvfs-backends
  gvfs-common
  gvfs-daemons
  gvfs-libs
  gwenview
  gwenview-doc
  gzip
  harvid
  hashcat
  hashcat-data
  hashdeep
  hashid
  hashrat
  hcxdumptool
  hcxkeys
  hcxtools
  hdf5-tools
  hdparm
  heartbleeder
  heif-gdk-pixbuf
  heif-thumbnailer
  hexcompare
  hexedit
  hfsplus
  hicolor-icon-theme
  horst
  hostname
  hping3
  hplip
  hplip-data
  html2text
  htop
  hunspell-en-us
  hunspell-pt-br
  hwdata
  hwinfo
  hwloc
  hydra
  hyphen-en-ca
  hyphen-fi
  hyphen-ga
  hyphen-id
  hyphen-pt-br
  i965-va-driver
  ibus-data
  ibus-gtk
  ibus-gtk3
  ibus-gtk4
  ibverbs-providers
  icoutils
  icu-devtools
  ieee-data
  iio-sensor-proxy
  ike-scan
  im-config
  imageindex
  imagemagick
  imagemagick-7-common
  imagemagick-7.q16
  imview
  inetutils-telnet
  info
  init
  init-system-helpers
  initramfs-tools
  initramfs-tools-bin
  initramfs-tools-core
  inkscape
  inputattach
  install-info
  intel-media-va-driver
  intel-microcode
  intltool-debian
  inxi
  ipgrab
  ipp-usb
  iproute2
  iptables
  iputils-ping
  iputils-tracepath
  ipv6toolkit
  ipxe-qemu
  ipxe-qemu-256k-compat-efi-roms
  ipython3
  isa-support
  iso-codes
  isoimagewriter
  isympy-common
  isympy3
  iucode-tool
  iw
  java-common
  java-wrappers
  javahelp2
  javascript-common
  jdupes
  jfsutils
  john
  john-data
  jose
  joystick
  jp2a
  jq
  jsbeautifier
  jtreg
  juk
  junit
  junit4
  kaccounts-integration
  kaccounts-providers
  kactivitymanagerd
  kaddressbook
  kaddressbook-data
  kajongg
  kalarm
  kalendarac
  kalgebra
  kalgebra-common
  kalzium
  kalzium-data
  kamera
  kamoso
  kanagram
  kanjidic
  kapman
  kapptemplate
  kasts
  kate
  kate-data
  katomic
  kbd
  kblackbox
  kblocks
  kbounce
  kbreakout
  kbruch
  kcachegrind
  kcalc
  kcharselect
  kcolorchooser
  kde-baseapps
  kde-cli-tools
  kde-cli-tools-data
  kde-config-cddb
  kde-config-cron
  kde-config-gtk-style
  kde-config-gtk-style-preview
  kde-config-plymouth
  kde-config-screenlocker
  kde-config-sddm
  kde-config-updates
  kde-full
  kde-inotify-survey
  kde-plasma-desktop
  kde-spectacle
  kde-standard
  kde-style-breeze
  kde-style-breeze-data
  kde-style-breeze-qt5
  kde-style-oxygen-qt6
  kdeaccessibility
  kdeadmin
  kdeconnect
  kdeconnect-libs
  kded5
  kded6
  kdeedu
  kdeedu-data
  kdeedu-kvtml-data
  kdegames
  kdegames-card-data
  kdegames-mahjongg-data-kf6
  kdegraphics
  kdegraphics-thumbnailers
  kdemultimedia
  kdenetwork
  kdenetwork-filesharing
  kdenlive
  kdenlive-data
  kdepim
  kdepim-addons
  kdepim-runtime
  kdepim-themeeditors
  kdeplasma-addons-data
  kdesdk
  kdesdk-scripts
  kdesdk-thumbnailers
  kdetoys
  kdeutils
  kdevelop
  kdevelop-data
  kdevelop-php
  kdevelop64-libs
  kdewebdev
  kdf
  kdialog
  kdiamond
  kdoctools6
  keditbookmarks
  keepassxc
  keepassxc-full
  keyboard-configuration
  keyutils
  kf6-breeze-icon-theme
  kfind
  kfourinline
  kgamma
  kgeography
  kgeography-data
  kget
  kget-doc
  kglobalacceld
  kgoldrunner
  kgpg
  khangman
  khelpcenter
  khelpcenter-data
  kig
  kigo
  killbots
  kimageformat6-plugins
  kimagemapeditor
  kinfocenter
  kio
  kio-admin
  kio-audiocd
  kio-audiocd-dev
  kio-extras
  kio-extras-data
  kio-fuse
  kio-gdrive
  kio-gopher
  kio-ldap
  kio-perldoc
  kio6
  kirigami-addons-data
  kiriki
  kiten
  kjumpingcube
  kleopatra
  klettres
  klettres-data
  klibc-utils
  klickety
  klines
  kmag
  kmahjongg
  kmail
  kmailtransport-plugins
  kmenuedit
  kmines
  kmod
  kmousetool
  kmouth
  kmplot
  knavalbattle
  knetwalk
  knights
  knighttime
  kolf
  kollision
  kolourpaint
  kompare
  konqueror
  konqueror-data
  konqueror-doc
  konquest
  konsole
  konsole-kpart
  konsolekalendar
  kontact
  kontrast
  korganizer
  kpackagelauncherqml
  kpackagetool5
  kpackagetool6
  kpart6-kompare
  kpartloader
  kpat
  krb5-locales
  krdc
  krecorder
  kreversi
  krfb
  kruler
  kscreen
  kshisen
  ksirk
  ksnakeduel
  kspaceduel
  ksquares
  ksshaskpass
  ksudoku
  ksystemlog
  ksystemstats
  kteatime
  ktimer
  ktouch
  ktouch-data
  ktuberling
  ktuberling-data
  kturtle
  kubrick
  kubuntu-desktop
  kubuntu-notification-helper
  kubuntu-restricted-addons
  kubuntu-restricted-extras
  kubuntu-settings-desktop
  kubuntu-wallpapers
  kuiviewer
  kunifiedpush
  kup-backup
  kwallet6
  kwalletmanager
  kwayland-integration
  kwayland5-data
  kwayland6-data
  kwin-addons
  kwin-common
  kwin-data
  kwin-decoration-oxygen
  kwin-style-aurorae
  kwin-style-breeze
  kwin-wayland
  kwordquiz
  kwrite
  kwrited
  lame
  language-pack-en
  language-pack-en-base
  language-pack-gnome-pt
  language-pack-gnome-pt-base
  language-pack-kde-pt
  language-pack-pt
  language-pack-pt-base
  language-selector-common
  laptop-detect
  layer-shell-qt
  lbzip2
  ldmtool
  ledit
  less
  lhasa
  lib2geom1.4.0
  lib32gcc-s1
  lib32stdc++6
  liba52-0.7.4
  libaa1
  libaacs0
  libabsl20260107
  libabw-0.1-1
  libaccounts-glib0
  libaccounts-qt6-1
  libaccountsservice0
  libacl1
  libadwaita-1-0
  libaec0
  libafflib0t64
  libaio1t64
  libakonadi-data
  libakonadicalendar-data
  libakonadisearch-bin
  libakonadisearch-data
  libakonadisearch-plugins
  libalgorithm-diff-perl
  libalgorithm-diff-xs-perl
  libalgorithm-merge-perl
  libaliased-perl
  libamd3
  libanalitza9
  libanalitzagui9
  libanalitzaplot9
  libanalitzawidgets9
  libancient2
  libantlr-java
  libantlr3-runtime-java
  libao-common
  libao4
  libaom3
  libaopalliance-java
  libapache-pom-java
  libapksig-java
  libapparmor1
  libappimage1.0abi1t64
  libappmenu-gtk3-parser0
  libappstream5
  libappstreamqt3
  libapr1t64
  libaprutil1t64
  libapt-pkg-perl
  libapt-pkg7.0
  libarchive-tools
  libarchive-zip-perl
  libarchive13t64
  libargon2-1
  libaribb24-0t64
  libarmadillo15
  libarpack2t64
  libasan8
  libasm-java
  libasm1t64
  libasmtools-java
  libasound2-data
  libasound2t64
  libaspell15
  libass9
  libassuan9
  libastro1
  libastyle3
  libasyncns0
  libatasmart4
  libatinject-jsr330-api-java
  libatk-bridge2.0-0t64
  libatk-wrapper-java
  libatk-wrapper-java-jni
  libatk1.0-0t64
  libatkmm-1.6-1v5
  libatomic1
  libatopology2t64
  libatspi2.0-0t64
  libattr1
  libaubio5
  libaudclient2
  libaudit-common
  libaudit1
  libaugeas0
  libauthen-sasl-perl
  libavahi-client3
  libavahi-common-data
  libavahi-common3
  libavahi-core7
  libavahi-glib1
  libavahi-ui-gtk3-0
  libavc1394-0
  libavcodec62
  libavdevice62
  libavfilter11
  libavformat62
  libavif16
  libavtp0
  libavutil60
  libayatana-appindicator3-1
  libayatana-ido3-0.4-0
  libayatana-indicator3-7
  libb-hooks-endofscope-perl
  libb-hooks-op-check-perl
  libb2-1
  libbabeltrace1
  libbabl-0.1-0
  libbaloowidgets-bin
  libbatterycontrol6
  libbcg729-0
  libbdplus0
  libberkeleydb-perl
  libbfio1
  libbinutils
  libblas-dev
  libblas3
  libblkid-dev
  libblkid1
  libblkio-dev
  libblkio1
  libblockdev-crypto3
  libblockdev-fs3
  libblockdev-loop3
  libblockdev-mdraid3
  libblockdev-nvme3
  libblockdev-part3
  libblockdev-smart3
  libblockdev-swap3
  libblockdev-utils3
  libblockdev3
  libblosc1
  libblosc2-7
  libbluetooth3
  libbluray3
  libboost-chrono1.90.0
  libboost-filesystem1.90.0
  libboost-iostreams1.90.0
  libboost-locale1.90.0
  libboost-program-options1.90.0
  libboost-python1.90.0
  libboost-thread1.90.0
  libbotan-3-10
  libbpf1
  libbpfcc
  libbrlapi0.8
  libbrotli-dev
  libbrotli1
  libbs2b0
  libbsd-dev
  libbsd0
  libbsh-java
  libbson2-2
  libburn4t64
  libbytesize-common
  libbytesize1
  libbz2-1.0
  libbz2-dev
  libbzip3-1
  libc-bin
  libc-dev-bin
  libc-gconv-modules-extra
  libc-icap-mod-virus-scan
  libc6
  libc6-dbg
  libc6-dev
  libc6-i386
  libcaca0
  libcacard0
  libcairo-gobject-perl
  libcairo-gobject2
  libcairo-perl
  libcairo-script-interpreter2
  libcairo2
  libcairomm-1.0-1v5
  libcalamares3.3
  libcalendarsupport-data
  libcamd3
  libcamel-1.2-64t64
  libcamlp-streams-ocaml
  libcanberra-pulse
  libcanberra0
  libcantorlibs-data
  libcantorlibs28abi2
  libcap-ng0
  libcap2
  libcap2-bin
  libcapstone-dev
  libcapstone5
  libcapture-tiny-perl
  libcares2
  libcbor0.10
  libcc1-0
  libccid
  libccolamd3
  libcddb2
  libcdi-api-java
  libcdio-cdda2t64
  libcdio-paranoia2t64
  libcdio19t64
  libcdparanoia0
  libcdr-0.1-1
  libcdt6
  libcfitsio10t64
  libcgi-fast-perl
  libcgi-pm-perl
  libcgraph8
  libchafa0t64
  libcharls2
  libchm1
  libcholmod5
  libchromaprint1
  libcjson1
  libclamav-client-perl
  libclamav-dev
  libclamav12
  libclamunrar
  libclamunrar12
  libclang-common-18-dev
  libclang-common-21-dev
  libclang-cpp18
  libclang-cpp21
  libclang-rt-18-dev
  libclang-rt-21-dev
  libclang1-18
  libclang1-21
  libclass-data-inheritable-perl
  libclass-inspector-perl
  libclass-method-modifiers-perl
  libclass-xsaccessor-perl
  libclone-perl
  libclucene-contribs1t64
  libclucene-core1t64
  libcodec2-1.2
  libcolamd3
  libcolord-gtk1t64
  libcolord2
  libcolorhug2
  libcom-err2
  libcommon-sense-perl
  libcommons-cli-java
  libcommons-codec-java
  libcommons-compress-java
  libcommons-io-java
  libcommons-lang3-java
  libcommons-logging-java
  libcommons-parent-java
  libcommons-text-java
  libcompiler-libs-ocaml-dev
  libcomposefs1
  libcompress-raw-lzma-perl
  libconfig-tiny-perl
  libconfig11
  libconst-fast-perl
  libcpanel-json-xs-perl
  libcpuinfo0
  libcrack2
  libcrypt-dev
  libcrypt-urandom-perl
  libcrypt1
  libcrypto++8t64
  libcryptsetup12
  libcsv3
  libctf-nobfd0
  libctf0
  libcue2
  libcups2t64
  libcupsfilters2-common
  libcupsfilters2t64
  libcupsimage2t64
  libcurl3t64-gnutls
  libcurl4t64
  libcwidget4
  libcwiid1t64
  libdaemon0
  libdata-dpath-perl
  libdata-dump-perl
  libdata-messagepack-perl
  libdata-optlist-perl
  libdata-validate-domain-perl
  libdata-validate-ip-perl
  libdata-validate-uri-perl
  libdate-manip-perl
  libdatrie1
  libdav1d7
  libdaxctl1
  libdb5.3t64
  libdbus-1-3
  libdbus-glib-1-2
  libdbusmenu-glib4
  libdbusmenu-gtk3-4
  libdbusmenu-qt5-2
  libdc1394-25
  libdca0
  libdconf1
  libddcutil5
  libde265-0
  libdebconf-kde1
  libdebconfclient0
  libdebuginfod-common
  libdebuginfod1t64
  libdecor-0-0
  libdecor-0-plugin-1-gtk
  libdeflate-dev
  libdeflate0
  libdevel-callchecker-perl
  libdevel-size-perl
  libdevel-stacktrace-perl
  libdevmapper-event1.02.1
  libdevmapper1.02.1
  libdigest-bubblebabble-perl
  libdigest-hmac-perl
  libdislocker0.7t64
  libdisplay-info-bin
  libdisplay-info3
  libdjvulibre-text
  libdjvulibre21
  libdmtx0t64
  libdnnl3.6
  libdolphinvcs6
  libdom4j-java
  libdotconf0
  libdouble-conversion3
  libdpkg-perl
  libdrm-amdgpu1
  libdrm-common
  libdrm-intel1
  libdrm-nouveau2
  libdrm-radeon1
  libdrm2
  libduktape207
  libdumbnet1
  libdv4t64
  libdvbpsi10
  libdvdnav4
  libdvdread8t64
  libdw1t64
  libdynaloader-functions-perl
  libe-book-0.1-1
  libeac3
  libebackend-1.2-11t64
  libebml5
  libebook-1.2-21t64
  libebook-contacts-1.2-4t64
  libebur128-1
  libedata-book-1.2-27t64
  libedataserver-1.2-27t64
  libedit2
  libeditorconfig0
  libefiboot1t64
  libefivar1t64
  libegl-mesa0
  libegl1
  libei1
  libeis1
  libel-api-java
  libelf1t64
  libemail-address-xs-perl
  libenchant-2-2
  libencode-locale-perl
  libengine-gost-openssl
  libengine-pkcs11-openssl
  libeot0
  libepoxy0
  libepub0
  libepubgen-0.1-1
  libequinox-osgi-java
  liberror-perl
  liberror-prone-java
  libespeak-ng1
  libestr0
  libetonyek-0.1-1
  libevdev-dev
  libevdev2
  libevdocument-4.0-6
  libevemu3t64
  libevent-2.1-7t64
  libeventviews-data
  libevview-4.0-5
  libewf2
  libexception-class-perl
  libexempi8
  libexif12
  libexiv2-28
  libexiv2-data
  libexpat1
  libexpat1-dev
  libext2fs2t64
  libexttextcat-2.0-0
  libexttextcat-data
  libextutils-depends-perl
  libfaad2
  libfakekey0
  libfakeroot
  libfalcosecurity0t64
  libfarmhash0
  libfastjson4
  libfbclient2
  libfcgi-bin
  libfcgi-perl
  libfcgi0t64
  libfdisk1
  libfdk-aac2
  libfdt1
  libfelix-framework-java
  libfelix-main-java
  libffi-dev
  libffi8
  libfftw3-double3
  libfftw3-single3
  libfido2-1
  libfile-basedir-perl
  libfile-desktopentry-perl
  libfile-fcntllock-perl
  libfile-find-rule-perl
  libfile-libmagic-perl
  libfile-listing-perl
  libfile-mimeinfo-perl
  libfile-sharedir-perl
  libflac++11
  libflac14
  libflashrom1
  libflite1
  libfltk-images1.3t64
  libfltk1.3t64
  libfluidsynth3
  libfmt10
  libfont-afm-perl
  libfont-ttf-perl
  libfontconfig-dev
  libfontconfig1
  libfontenc1
  libfontforge4
  libfprint-2-2
  libfprint-2-tod1
  libfreeaptx0
  libfreecell-solver0
  libfreehand-0.1-1
  libfreerdp-client3-3
  libfreerdp3-3
  libfreetype-dev
  libfreetype6
  libfreexl1
  libfreezethaw-perl
  libfribidi0
  libfsverity0
  libftdi1-2
  libfuse3-4
  libfuturesql6-0
  libfwupd3
  libfyaml0
  libfyba0t64
  libgail-common
  libgail18t64
  libgav1-2
  libgavl3
  libgbm1
  libgc1
  libgcc-15-dev
  libgcc-s1
  libgck-1-0
  libgck-2-2
  libgcr-4-4
  libgcr-base-3-1
  libgcr-ui-3-1
  libgcrypt20
  libgd3
  libgdal38
  libgdbm-compat4t64
  libgdbm6t64
  libgdcm3.0t64
  libgdiplus
  libgdk-pixbuf-2.0-0
  libgdk-pixbuf2.0-common
  libgedit-amtk-5-0
  libgedit-amtk-5-common
  libgedit-gfls-1-0
  libgedit-gfls-common
  libgedit-gtksourceview-300-3
  libgedit-gtksourceview-300-common
  libgedit-tepl-6-3
  libgedit-tepl-common
  libgee-0.8-2
  libgegl-0.4-0t64
  libgegl-common
  libgeoclue-2-0
  libgeocode-glib-2-0
  libgeoip1t64
  libgeos-c1t64
  libgeos3.14.1
  libgeotiff5
  libgeronimo-annotation-1.3-spec-java
  libgeronimo-interceptor-3.0-spec-java
  libgettextpo0
  libgexiv2-2
  libgfortran-15-dev
  libgfortran5
  libgif7
  libgimp-3.0-0
  libgio-2.0-dev
  libgio-2.0-dev-bin
  libgirepository-1.0-1
  libgirepository-2.0-0
  libgit2-1.9
  libgjs0
  libgl-dev
  libgl1
  libgl1-mesa-dri
  libgles2
  libglib-object-introspection-perl
  libglib-perl
  libglib2.0-0t64
  libglib2.0-bin
  libglib2.0-data
  libglib2.0-dev
  libglib2.0-dev-bin
  libglibmm-2.4-1t64
  libglobalplatform7
  libglu1-mesa
  libglu1-mesa-dev
  libglut-dev
  libglut3.12
  libglvnd0
  libglx-dev
  libglx-mesa0
  libglx0
  libglycin-2-0
  libgme0
  libgmic1
  libgmp-dev
  libgmp10
  libgmpxx4ldbl
  libgnome-desktop-4-2t64
  libgnustep-base1.31
  libgnutls-dane0t64
  libgnutls30t64
  libgoa-1.0-0b
  libgoa-1.0-common
  libgoffice-0.10-10-common
  libgoffice-0.10-10t64
  libgomp1
  libgpg-error-l10n
  libgpg-error0
  libgpgme45
  libgpgmepp7
  libgphoto2-6t64
  libgphoto2-l10n
  libgphoto2-port12t64
  libgpm2
  libgppcscconnectionplugin1
  libgprofng0
  libgps32
  libgranite-common
  libgranite6
  libgrantleetheme-data
  libgrantleetheme-plugins
  libgraphene-1.0-0
  libgraphicsmagick++-q16-12t64
  libgraphicsmagick-q16-3t64
  libgraphite2-3
  libgravatar-data
  libgrpc++1.51t64
  libgrpc29t64
  libgs-common
  libgs10
  libgs10-common
  libgsecuredelete0
  libgsf-1-114
  libgsf-1-common
  libgsl28
  libgslcblas0
  libgsm1
  libgspell-1-3
  libgspell-1-common
  libgssapi-krb5-2
  libgssdp-1.6-0
  libgstreamer-gl1.0-0
  libgstreamer-plugins-bad1.0-0
  libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-extra1.0-0
  libgstreamer1.0-0
  libgtk-3-0t64
  libgtk-3-bin
  libgtk-3-common
  libgtk-4-1
  libgtk-4-bin
  libgtk-4-common
  libgtk2.0-0t64
  libgtk2.0-bin
  libgtk2.0-common
  libgtk3-perl
  libgtkmm-3.0-1t64
  libgtksourceview-4-0
  libgtksourceview-4-common
  libguava-java
  libgucharmap-2-90-7
  libgudev-1.0-0
  libgudev-1.0-dev
  libguestfs-hfsplus
  libguestfs-perl
  libguestfs-tools
  libguestfs-xfs
  libguestfs0t64
  libguice-java
  libgumbo3
  libgupnp-1.6-0
  libgupnp-igd-1.6-0
  libgusb2a
  libgutenprint-common
  libgutenprint9
  libguytools2t64
  libgvc7
  libgvplugin-gd8
  libgvplugin-pango8
  libgvpr2
  libgweather-4-0t64
  libgweather-4-common
  libgxps2t64
  libhamcrest-java
  libhandy-1-0
  libharfbuzz-gobject0
  libharfbuzz-icu0
  libharfbuzz-subset0
  libharfbuzz0b
  libhashkit2t64
  libhd21t64
  libhdf4-0
  libhdf5-310
  libhdf5-hl-310
  libheif-plugin-aomdec
  libheif-plugin-aomenc
  libheif-plugin-j2kdec
  libheif-plugin-libde265
  libheif-plugin-x265
  libheif1
  libhfsp0t64
  libhfstospell11
  libhivex0
  libhogweed6t64
  libhpmud0
  libhsqldb1.8.0-java
  libhtml-form-perl
  libhtml-format-perl
  libhtml-html5-entities-perl
  libhtml-parser-perl
  libhtml-tagset-perl
  libhtml-tokeparser-simple-perl
  libhtml-tree-perl
  libhttp-cookies-perl
  libhttp-daemon-perl
  libhttp-date-perl
  libhttp-message-perl
  libhttp-negotiate-perl
  libhttp-parser2.9
  libhunspell-1.7-0
  libhwasan0
  libhwloc-plugins
  libhwloc15
  libhwy1t64
  libhyphen0
  libibus-1.0-5
  libibverbs1
  libical3t64
  libicapapi5t64
  libice-dev
  libice-doc
  libice6
  libicu-dev
  libicu4j-java
  libicu78
  libid3tag0
  libidn12
  libidn2-0
  libiec61883-0
  libieee1284-3t64
  libigdgmm12
  libijs-0.35
  libimage-base-bundle-perl
  libimage-exiftool-perl
  libimage-info-perl
  libimage-magick-perl
  libimage-magick-q16-perl
  libimagequant0
  libimath-3-1-29t64
  libimlib2t64
  libimobiledevice-1.0-6
  libimobiledevice-glue-1.0-0
  libimport-into-perl
  libinchi1.07
  libincidenceeditor-data
  libinih1
  libiniparser4
  libinireader0
  libinput-bin
  libinput-dev
  libinput10
  libinstpatch-1.0-2
  libintellij-annotations-java
  libintl-perl
  libintl-xs-perl
  libio-compress-brotli-perl
  libio-html-perl
  libio-interactive-perl
  libio-socket-ssl-perl
  libio-string-perl
  libio-stringy-perl
  libip4tc2
  libip6tc2
  libipc-run3-perl
  libipc-system-simple-perl
  libipt2
  libircclient1
  libiscsi7
  libisl23
  libisoburn1t64
  libisofs6t64
  libiterator-perl
  libiterator-util-perl
  libitm1
  libiw30t64
  libixml11t64
  libjack-jackd2-0
  libjansi-java
  libjansson4
  libjavaparser-java
  libjavascriptcoregtk-6.0-1
  libjaxen-java
  libjbig0
  libjbig2dec0
  libjcat1
  libjcommander-java
  libjdom1-java
  libjemalloc2
  libjetbrains-annotations-java
  libjna-java
  libjna-jni
  libjna-platform-java
  libjodycode4
  libjose0
  libjpeg-dev
  libjpeg-turbo-progs
  libjpeg-turbo8
  libjpeg-turbo8-dev
  libjpeg8
  libjpeg8-dev
  libjq1
  libjs-jquery
  libjs-jquery-ui
  libjs-jquery-ui-theme-base
  libjs-sphinxdoc
  libjs-underscore
  libjson-c5
  libjson-glib-1.0-0
  libjson-glib-1.0-common
  libjson-maybexs-perl
  libjson-perl
  libjson-simple-java
  libjson-xs-perl
  libjsoncpp26
  libjsoup-java
  libjsp-api-java
  libjsr305-java
  libjtharness-java
  libjudydebian1
  libjxl-gdk-pixbuf
  libjxl0.11
  libjxr-tools
  libjxr0t64
  libk3b-extracodecs
  libk3b8t64
  libk5crypto3
  libkaccounts6-2
  libkasten4controllers0
  libkasten4core0
  libkasten4gui0
  libkasten4okteta2controllers0
  libkasten4okteta2core0
  libkasten4okteta2gui0
  libkate1
  libkcalendarutils-data
  libkcddb6-5
  libkcddb6-dev
  libkcolorpicker-qt6-0
  libkcompactdisc6-5
  libkdcrawqt6-5
  libkddockwidgets-qt6-3
  libkdecorations3-6
  libkdecorations3private2
  libkdegames6-6
  libkdegames6-i18n
  libkdegames6private6
  libkdepim-data
  libkdepim-plugins
  libkdsoap-qt6-2
  libkdsoapwsdiscoveryclient0
  libkeduvocdocument-data
  libkeduvocdocument5abi2
  libkexiv2qt6-0
  libkeyutils1
  libkf5archive-data
  libkf5archive5
  libkf5attica5
  libkf5auth-data
  libkf5auth5
  libkf5authcore5
  libkf5bookmarks-data
  libkf5bookmarks5
  libkf5codecs-data
  libkf5codecs5
  libkf5completion-data
  libkf5completion5
  libkf5config-bin
  libkf5config-data
  libkf5configcore5
  libkf5configgui5
  libkf5configwidgets-data
  libkf5configwidgets5
  libkf5coreaddons-data
  libkf5coreaddons5
  libkf5crash5
  libkf5dbusaddons-bin
  libkf5dbusaddons-data
  libkf5dbusaddons5
  libkf5declarative-data
  libkf5declarative5
  libkf5doctools5
  libkf5globalaccel-bin
  libkf5globalaccel-data
  libkf5globalaccel5
  libkf5globalaccelprivate5
  libkf5guiaddons-bin
  libkf5guiaddons-data
  libkf5guiaddons5
  libkf5i18n-data
  libkf5i18n5
  libkf5iconthemes-bin
  libkf5iconthemes-data
  libkf5iconthemes5
  libkf5itemviews-data
  libkf5itemviews5
  libkf5jobwidgets-data
  libkf5jobwidgets5
  libkf5kcmutils-data
  libkf5kcmutils5
  libkf5kcmutilscore5
  libkf5kiocore5
  libkf5kiofilewidgets5
  libkf5kiogui5
  libkf5kiontlm5
  libkf5kiowidgets5
  libkf5kirigami2-5
  libkf5newstuff-data
  libkf5newstuff5
  libkf5newstuffcore5
  libkf5notifications-data
  libkf5notifications5
  libkf5package-data
  libkf5package5
  libkf5parts-data
  libkf5parts-plugins
  libkf5parts5
  libkf5quickaddons5
  libkf5service-bin
  libkf5service-data
  libkf5service5
  libkf5solid5
  libkf5solid5-data
  libkf5sonnet5-data
  libkf5sonnetcore5
  libkf5sonnetui5
  libkf5style5
  libkf5syndication5abi1
  libkf5textwidgets-data
  libkf5textwidgets5
  libkf5wallet-bin
  libkf5wallet-data
  libkf5wallet5
  libkf5waylandclient5
  libkf5widgetsaddons-data
  libkf5widgetsaddons5
  libkf5windowsystem-data
  libkf5windowsystem5
  libkf5xmlgui-bin
  libkf5xmlgui-data
  libkf5xmlgui5
  libkf6archive-data
  libkf6archive-dev
  libkf6archive-doc
  libkf6archive6
  libkf6attica6
  libkf6auth-data
  libkf6authcore6
  libkf6baloo6
  libkf6balooengine6
  libkf6baloowidgets6
  libkf6bluezqt-data
  libkf6bluezqt6
  libkf6bookmarks-data
  libkf6bookmarks-dev
  libkf6bookmarks-doc
  libkf6bookmarks6
  libkf6bookmarkswidgets6
  libkf6breezeicons6
  libkf6calendarcore6
  libkf6calendarevents6
  libkf6codecs-data
  libkf6codecs-dev
  libkf6codecs-doc
  libkf6codecs6
  libkf6colorscheme-data
  libkf6colorscheme-dev
  libkf6colorscheme-doc
  libkf6colorscheme6
  libkf6completion-data
  libkf6completion-dev
  libkf6completion-doc
  libkf6completion6
  libkf6config-bin
  libkf6config-data
  libkf6config-dev
  libkf6config-dev-bin
  libkf6config-doc
  libkf6configcore6
  libkf6configgui6
  libkf6configqml6
  libkf6configwidgets-data
  libkf6configwidgets-dev
  libkf6configwidgets-doc
  libkf6configwidgets6
  libkf6contacts-data
  libkf6contacts6
  libkf6coreaddons-data
  libkf6coreaddons-dev
  libkf6coreaddons-doc
  libkf6coreaddons6
  libkf6crash6
  libkf6dav-data
  libkf6dav6
  libkf6dbusaddons-bin
  libkf6dbusaddons-data
  libkf6dbusaddons6
  libkf6declarative-data
  libkf6dnssd-data
  libkf6dnssd6
  libkf6doctools-dev
  libkf6doctools-doc
  libkf6doctools6
  libkf6filemetadata-bin
  libkf6filemetadata-data
  libkf6filemetadata3
  libkf6globalaccel-data
  libkf6globalaccel6
  libkf6guiaddons-bin
  libkf6guiaddons-data
  libkf6guiaddons-dev
  libkf6guiaddons-doc
  libkf6guiaddons6
  libkf6holidays-data
  libkf6holidays6
  libkf6i18n-data
  libkf6i18n-dev
  libkf6i18n-doc
)

# Instala a lista de pacotes APT (ignora pacotes que eventualmente mudarem de nome nas novas versões)
sudo apt install -y "${PACOTES_APT[@]}" || true

echo "=== 7. Instalando pacotes via Snap ==="

PACOTES_SNAP=(
  bare
  code
  core18
  core20
  core22
  core24
  gnome-3-28-1804
  gnome-46-2404
  gtk-common-themes
  mesa-2404
  metasploit-framework
  shortwave
  sublime-text
  teams-for-linux
  telegram-desktop
  thunderbird
  whatsapp-linux-app
  youtube-music-desktop-app
  zaproxy
)

# Laço para lidar automaticamente com instâncias que necessitam de flag --classic
for snap_pkg in "${PACOTES_SNAP[@]}"; do
  if [[ "$snap_pkg" == "code" || "$snap_pkg" == "sublime-text" ]]; then
    sudo snap install "$snap_pkg" --classic || true
  else
    sudo snap install "$snap_pkg" || true
  fi
done

echo "=== 8. Instalando pacotes via Flatpak ==="

PACOTES_FLATPAK=(
  # Reservado para eventuais adições via Flathub.
)

if [ ${#PACOTES_FLATPAK[@]} -gt 0 ]; then
  flatpak install -y flathub "${PACOTES_FLATPAK[@]}" || true
fi

echo "=== 9. Download e Instalação do Google Chrome (.deb oficial) ==="
wget -O /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install -y /tmp/google-chrome-stable_current_amd64.deb
rm -f /tmp/google-chrome-stable_current_amd64.deb

echo "=== 10. Limpeza e finalização ==="
sudo apt autoremove -y
sudo apt clean

echo "=== Processo de pós-instalação e restauração concluído com sucesso! ==="
